//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("rlworldwideModel", "FK_icg_marketing_data_supplement_icg_marketing_data", "icg_marketing_data", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Unity.Mvc3.Example.icg_marketing_data), "icg_marketing_data_supplement", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Unity.Mvc3.Example.icg_marketing_data_supplement), true)]

#endregion

namespace Unity.Mvc3.Example
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class rlworldwideEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new rlworldwideEntities1 object using the connection string found in the 'rlworldwideEntities1' section of the application configuration file.
        /// </summary>
        public rlworldwideEntities1() : base("name=rlworldwideEntities1", "rlworldwideEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new rlworldwideEntities1 object.
        /// </summary>
        public rlworldwideEntities1(string connectionString) : base(connectionString, "rlworldwideEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new rlworldwideEntities1 object.
        /// </summary>
        public rlworldwideEntities1(EntityConnection connection) : base(connection, "rlworldwideEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<icg_marketing_data> icg_marketing_data
        {
            get
            {
                if ((_icg_marketing_data == null))
                {
                    _icg_marketing_data = base.CreateObjectSet<icg_marketing_data>("icg_marketing_data");
                }
                return _icg_marketing_data;
            }
        }
        private ObjectSet<icg_marketing_data> _icg_marketing_data;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<icg_marketing_data_sitenum> icg_marketing_data_sitenum
        {
            get
            {
                if ((_icg_marketing_data_sitenum == null))
                {
                    _icg_marketing_data_sitenum = base.CreateObjectSet<icg_marketing_data_sitenum>("icg_marketing_data_sitenum");
                }
                return _icg_marketing_data_sitenum;
            }
        }
        private ObjectSet<icg_marketing_data_sitenum> _icg_marketing_data_sitenum;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<icg_marketing_data_supplement> icg_marketing_data_supplement
        {
            get
            {
                if ((_icg_marketing_data_supplement == null))
                {
                    _icg_marketing_data_supplement = base.CreateObjectSet<icg_marketing_data_supplement>("icg_marketing_data_supplement");
                }
                return _icg_marketing_data_supplement;
            }
        }
        private ObjectSet<icg_marketing_data_supplement> _icg_marketing_data_supplement;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the icg_marketing_data EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToicg_marketing_data(icg_marketing_data icg_marketing_data)
        {
            base.AddObject("icg_marketing_data", icg_marketing_data);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the icg_marketing_data_sitenum EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToicg_marketing_data_sitenum(icg_marketing_data_sitenum icg_marketing_data_sitenum)
        {
            base.AddObject("icg_marketing_data_sitenum", icg_marketing_data_sitenum);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the icg_marketing_data_supplement EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToicg_marketing_data_supplement(icg_marketing_data_supplement icg_marketing_data_supplement)
        {
            base.AddObject("icg_marketing_data_supplement", icg_marketing_data_supplement);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="icg_cap_site">No Metadata Documentation available.</param>
        /// <param name="prefix">No Metadata Documentation available.</param>
        /// <param name="firstName">No Metadata Documentation available.</param>
        /// <param name="lastName">No Metadata Documentation available.</param>
        /// <param name="emailAddress">No Metadata Documentation available.</param>
        /// <param name="phoneNumber">No Metadata Documentation available.</param>
        /// <param name="address1">No Metadata Documentation available.</param>
        /// <param name="address2">No Metadata Documentation available.</param>
        /// <param name="city">No Metadata Documentation available.</param>
        /// <param name="state">No Metadata Documentation available.</param>
        /// <param name="country">No Metadata Documentation available.</param>
        /// <param name="register">No Metadata Documentation available.</param>
        /// <param name="isCustomer">No Metadata Documentation available.</param>
        /// <param name="subject">No Metadata Documentation available.</param>
        /// <param name="message">No Metadata Documentation available.</param>
        /// <param name="rl_store">No Metadata Documentation available.</param>
        /// <param name="heardAboutUs">No Metadata Documentation available.</param>
        public int usp_SaveMarketingCapture(global::System.String icg_cap_site, global::System.String prefix, global::System.String firstName, global::System.String lastName, global::System.String emailAddress, global::System.String phoneNumber, global::System.String address1, global::System.String address2, global::System.String city, global::System.String state, global::System.String country, Nullable<global::System.Boolean> register, Nullable<global::System.Boolean> isCustomer, global::System.String subject, global::System.String message, global::System.String rl_store, global::System.String heardAboutUs)
        {
            ObjectParameter icg_cap_siteParameter;
            if (icg_cap_site != null)
            {
                icg_cap_siteParameter = new ObjectParameter("icg_cap_site", icg_cap_site);
            }
            else
            {
                icg_cap_siteParameter = new ObjectParameter("icg_cap_site", typeof(global::System.String));
            }
    
            ObjectParameter prefixParameter;
            if (prefix != null)
            {
                prefixParameter = new ObjectParameter("prefix", prefix);
            }
            else
            {
                prefixParameter = new ObjectParameter("prefix", typeof(global::System.String));
            }
    
            ObjectParameter firstNameParameter;
            if (firstName != null)
            {
                firstNameParameter = new ObjectParameter("firstName", firstName);
            }
            else
            {
                firstNameParameter = new ObjectParameter("firstName", typeof(global::System.String));
            }
    
            ObjectParameter lastNameParameter;
            if (lastName != null)
            {
                lastNameParameter = new ObjectParameter("lastName", lastName);
            }
            else
            {
                lastNameParameter = new ObjectParameter("lastName", typeof(global::System.String));
            }
    
            ObjectParameter emailAddressParameter;
            if (emailAddress != null)
            {
                emailAddressParameter = new ObjectParameter("emailAddress", emailAddress);
            }
            else
            {
                emailAddressParameter = new ObjectParameter("emailAddress", typeof(global::System.String));
            }
    
            ObjectParameter phoneNumberParameter;
            if (phoneNumber != null)
            {
                phoneNumberParameter = new ObjectParameter("phoneNumber", phoneNumber);
            }
            else
            {
                phoneNumberParameter = new ObjectParameter("phoneNumber", typeof(global::System.String));
            }
    
            ObjectParameter address1Parameter;
            if (address1 != null)
            {
                address1Parameter = new ObjectParameter("address1", address1);
            }
            else
            {
                address1Parameter = new ObjectParameter("address1", typeof(global::System.String));
            }
    
            ObjectParameter address2Parameter;
            if (address2 != null)
            {
                address2Parameter = new ObjectParameter("address2", address2);
            }
            else
            {
                address2Parameter = new ObjectParameter("address2", typeof(global::System.String));
            }
    
            ObjectParameter cityParameter;
            if (city != null)
            {
                cityParameter = new ObjectParameter("city", city);
            }
            else
            {
                cityParameter = new ObjectParameter("city", typeof(global::System.String));
            }
    
            ObjectParameter stateParameter;
            if (state != null)
            {
                stateParameter = new ObjectParameter("state", state);
            }
            else
            {
                stateParameter = new ObjectParameter("state", typeof(global::System.String));
            }
    
            ObjectParameter countryParameter;
            if (country != null)
            {
                countryParameter = new ObjectParameter("country", country);
            }
            else
            {
                countryParameter = new ObjectParameter("country", typeof(global::System.String));
            }
    
            ObjectParameter registerParameter;
            if (register.HasValue)
            {
                registerParameter = new ObjectParameter("register", register);
            }
            else
            {
                registerParameter = new ObjectParameter("register", typeof(global::System.Boolean));
            }
    
            ObjectParameter isCustomerParameter;
            if (isCustomer.HasValue)
            {
                isCustomerParameter = new ObjectParameter("isCustomer", isCustomer);
            }
            else
            {
                isCustomerParameter = new ObjectParameter("isCustomer", typeof(global::System.Boolean));
            }
    
            ObjectParameter subjectParameter;
            if (subject != null)
            {
                subjectParameter = new ObjectParameter("subject", subject);
            }
            else
            {
                subjectParameter = new ObjectParameter("subject", typeof(global::System.String));
            }
    
            ObjectParameter messageParameter;
            if (message != null)
            {
                messageParameter = new ObjectParameter("message", message);
            }
            else
            {
                messageParameter = new ObjectParameter("message", typeof(global::System.String));
            }
    
            ObjectParameter rl_storeParameter;
            if (rl_store != null)
            {
                rl_storeParameter = new ObjectParameter("rl_store", rl_store);
            }
            else
            {
                rl_storeParameter = new ObjectParameter("rl_store", typeof(global::System.String));
            }
    
            ObjectParameter heardAboutUsParameter;
            if (heardAboutUs != null)
            {
                heardAboutUsParameter = new ObjectParameter("heardAboutUs", heardAboutUs);
            }
            else
            {
                heardAboutUsParameter = new ObjectParameter("heardAboutUs", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("usp_SaveMarketingCapture", icg_cap_siteParameter, prefixParameter, firstNameParameter, lastNameParameter, emailAddressParameter, phoneNumberParameter, address1Parameter, address2Parameter, cityParameter, stateParameter, countryParameter, registerParameter, isCustomerParameter, subjectParameter, messageParameter, rl_storeParameter, heardAboutUsParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rlworldwideModel", Name="icg_marketing_data")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class icg_marketing_data : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new icg_marketing_data object.
        /// </summary>
        /// <param name="icg_cap_id">Initial value of the icg_cap_id property.</param>
        public static icg_marketing_data Createicg_marketing_data(global::System.Int32 icg_cap_id)
        {
            icg_marketing_data icg_marketing_data = new icg_marketing_data();
            icg_marketing_data.icg_cap_id = icg_cap_id;
            return icg_marketing_data;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 icg_cap_id
        {
            get
            {
                return _icg_cap_id;
            }
            set
            {
                if (_icg_cap_id != value)
                {
                    Onicg_cap_idChanging(value);
                    ReportPropertyChanging("icg_cap_id");
                    _icg_cap_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("icg_cap_id");
                    Onicg_cap_idChanged();
                }
            }
        }
        private global::System.Int32 _icg_cap_id;
        partial void Onicg_cap_idChanging(global::System.Int32 value);
        partial void Onicg_cap_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_site
        {
            get
            {
                return _icg_cap_site;
            }
            set
            {
                Onicg_cap_siteChanging(value);
                ReportPropertyChanging("icg_cap_site");
                _icg_cap_site = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_site");
                Onicg_cap_siteChanged();
            }
        }
        private global::System.String _icg_cap_site;
        partial void Onicg_cap_siteChanging(global::System.String value);
        partial void Onicg_cap_siteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_email
        {
            get
            {
                return _icg_cap_email;
            }
            set
            {
                Onicg_cap_emailChanging(value);
                ReportPropertyChanging("icg_cap_email");
                _icg_cap_email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_email");
                Onicg_cap_emailChanged();
            }
        }
        private global::System.String _icg_cap_email;
        partial void Onicg_cap_emailChanging(global::System.String value);
        partial void Onicg_cap_emailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_prefix
        {
            get
            {
                return _icg_cap_prefix;
            }
            set
            {
                Onicg_cap_prefixChanging(value);
                ReportPropertyChanging("icg_cap_prefix");
                _icg_cap_prefix = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_prefix");
                Onicg_cap_prefixChanged();
            }
        }
        private global::System.String _icg_cap_prefix;
        partial void Onicg_cap_prefixChanging(global::System.String value);
        partial void Onicg_cap_prefixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_fname
        {
            get
            {
                return _icg_cap_fname;
            }
            set
            {
                Onicg_cap_fnameChanging(value);
                ReportPropertyChanging("icg_cap_fname");
                _icg_cap_fname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_fname");
                Onicg_cap_fnameChanged();
            }
        }
        private global::System.String _icg_cap_fname;
        partial void Onicg_cap_fnameChanging(global::System.String value);
        partial void Onicg_cap_fnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_lname
        {
            get
            {
                return _icg_cap_lname;
            }
            set
            {
                Onicg_cap_lnameChanging(value);
                ReportPropertyChanging("icg_cap_lname");
                _icg_cap_lname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_lname");
                Onicg_cap_lnameChanged();
            }
        }
        private global::System.String _icg_cap_lname;
        partial void Onicg_cap_lnameChanging(global::System.String value);
        partial void Onicg_cap_lnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_address1
        {
            get
            {
                return _icg_cap_address1;
            }
            set
            {
                Onicg_cap_address1Changing(value);
                ReportPropertyChanging("icg_cap_address1");
                _icg_cap_address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_address1");
                Onicg_cap_address1Changed();
            }
        }
        private global::System.String _icg_cap_address1;
        partial void Onicg_cap_address1Changing(global::System.String value);
        partial void Onicg_cap_address1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_address2
        {
            get
            {
                return _icg_cap_address2;
            }
            set
            {
                Onicg_cap_address2Changing(value);
                ReportPropertyChanging("icg_cap_address2");
                _icg_cap_address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_address2");
                Onicg_cap_address2Changed();
            }
        }
        private global::System.String _icg_cap_address2;
        partial void Onicg_cap_address2Changing(global::System.String value);
        partial void Onicg_cap_address2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_address3
        {
            get
            {
                return _icg_cap_address3;
            }
            set
            {
                Onicg_cap_address3Changing(value);
                ReportPropertyChanging("icg_cap_address3");
                _icg_cap_address3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_address3");
                Onicg_cap_address3Changed();
            }
        }
        private global::System.String _icg_cap_address3;
        partial void Onicg_cap_address3Changing(global::System.String value);
        partial void Onicg_cap_address3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_city
        {
            get
            {
                return _icg_cap_city;
            }
            set
            {
                Onicg_cap_cityChanging(value);
                ReportPropertyChanging("icg_cap_city");
                _icg_cap_city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_city");
                Onicg_cap_cityChanged();
            }
        }
        private global::System.String _icg_cap_city;
        partial void Onicg_cap_cityChanging(global::System.String value);
        partial void Onicg_cap_cityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_state
        {
            get
            {
                return _icg_cap_state;
            }
            set
            {
                Onicg_cap_stateChanging(value);
                ReportPropertyChanging("icg_cap_state");
                _icg_cap_state = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_state");
                Onicg_cap_stateChanged();
            }
        }
        private global::System.String _icg_cap_state;
        partial void Onicg_cap_stateChanging(global::System.String value);
        partial void Onicg_cap_stateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_province
        {
            get
            {
                return _icg_cap_province;
            }
            set
            {
                Onicg_cap_provinceChanging(value);
                ReportPropertyChanging("icg_cap_province");
                _icg_cap_province = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_province");
                Onicg_cap_provinceChanged();
            }
        }
        private global::System.String _icg_cap_province;
        partial void Onicg_cap_provinceChanging(global::System.String value);
        partial void Onicg_cap_provinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_zip
        {
            get
            {
                return _icg_cap_zip;
            }
            set
            {
                Onicg_cap_zipChanging(value);
                ReportPropertyChanging("icg_cap_zip");
                _icg_cap_zip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_zip");
                Onicg_cap_zipChanged();
            }
        }
        private global::System.String _icg_cap_zip;
        partial void Onicg_cap_zipChanging(global::System.String value);
        partial void Onicg_cap_zipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_country
        {
            get
            {
                return _icg_cap_country;
            }
            set
            {
                Onicg_cap_countryChanging(value);
                ReportPropertyChanging("icg_cap_country");
                _icg_cap_country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_country");
                Onicg_cap_countryChanged();
            }
        }
        private global::System.String _icg_cap_country;
        partial void Onicg_cap_countryChanging(global::System.String value);
        partial void Onicg_cap_countryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_mphone
        {
            get
            {
                return _icg_cap_mphone;
            }
            set
            {
                Onicg_cap_mphoneChanging(value);
                ReportPropertyChanging("icg_cap_mphone");
                _icg_cap_mphone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_mphone");
                Onicg_cap_mphoneChanged();
            }
        }
        private global::System.String _icg_cap_mphone;
        partial void Onicg_cap_mphoneChanging(global::System.String value);
        partial void Onicg_cap_mphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_hphone
        {
            get
            {
                return _icg_cap_hphone;
            }
            set
            {
                Onicg_cap_hphoneChanging(value);
                ReportPropertyChanging("icg_cap_hphone");
                _icg_cap_hphone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_hphone");
                Onicg_cap_hphoneChanged();
            }
        }
        private global::System.String _icg_cap_hphone;
        partial void Onicg_cap_hphoneChanging(global::System.String value);
        partial void Onicg_cap_hphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_ccode
        {
            get
            {
                return _icg_cap_ccode;
            }
            set
            {
                Onicg_cap_ccodeChanging(value);
                ReportPropertyChanging("icg_cap_ccode");
                _icg_cap_ccode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_ccode");
                Onicg_cap_ccodeChanged();
            }
        }
        private global::System.String _icg_cap_ccode;
        partial void Onicg_cap_ccodeChanging(global::System.String value);
        partial void Onicg_cap_ccodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_age
        {
            get
            {
                return _icg_cap_age;
            }
            set
            {
                Onicg_cap_ageChanging(value);
                ReportPropertyChanging("icg_cap_age");
                _icg_cap_age = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_age");
                Onicg_cap_ageChanged();
            }
        }
        private global::System.String _icg_cap_age;
        partial void Onicg_cap_ageChanging(global::System.String value);
        partial void Onicg_cap_ageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_gender
        {
            get
            {
                return _icg_cap_gender;
            }
            set
            {
                Onicg_cap_genderChanging(value);
                ReportPropertyChanging("icg_cap_gender");
                _icg_cap_gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_gender");
                Onicg_cap_genderChanged();
            }
        }
        private global::System.String _icg_cap_gender;
        partial void Onicg_cap_genderChanging(global::System.String value);
        partial void Onicg_cap_genderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> icg_cap_optdot
        {
            get
            {
                return _icg_cap_optdot;
            }
            set
            {
                Onicg_cap_optdotChanging(value);
                ReportPropertyChanging("icg_cap_optdot");
                _icg_cap_optdot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_optdot");
                Onicg_cap_optdotChanged();
            }
        }
        private Nullable<global::System.Byte> _icg_cap_optdot;
        partial void Onicg_cap_optdotChanging(Nullable<global::System.Byte> value);
        partial void Onicg_cap_optdotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> icg_cap_opthome
        {
            get
            {
                return _icg_cap_opthome;
            }
            set
            {
                Onicg_cap_opthomeChanging(value);
                ReportPropertyChanging("icg_cap_opthome");
                _icg_cap_opthome = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_opthome");
                Onicg_cap_opthomeChanged();
            }
        }
        private Nullable<global::System.Byte> _icg_cap_opthome;
        partial void Onicg_cap_opthomeChanging(Nullable<global::System.Byte> value);
        partial void Onicg_cap_opthomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> icg_cap_optrun
        {
            get
            {
                return _icg_cap_optrun;
            }
            set
            {
                Onicg_cap_optrunChanging(value);
                ReportPropertyChanging("icg_cap_optrun");
                _icg_cap_optrun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_optrun");
                Onicg_cap_optrunChanged();
            }
        }
        private Nullable<global::System.Byte> _icg_cap_optrun;
        partial void Onicg_cap_optrunChanging(Nullable<global::System.Byte> value);
        partial void Onicg_cap_optrunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> icg_cap_optrlg
        {
            get
            {
                return _icg_cap_optrlg;
            }
            set
            {
                Onicg_cap_optrlgChanging(value);
                ReportPropertyChanging("icg_cap_optrlg");
                _icg_cap_optrlg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_optrlg");
                Onicg_cap_optrlgChanged();
            }
        }
        private Nullable<global::System.Byte> _icg_cap_optrlg;
        partial void Onicg_cap_optrlgChanging(Nullable<global::System.Byte> value);
        partial void Onicg_cap_optrlgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> icg_cap_optrgb
        {
            get
            {
                return _icg_cap_optrgb;
            }
            set
            {
                Onicg_cap_optrgbChanging(value);
                ReportPropertyChanging("icg_cap_optrgb");
                _icg_cap_optrgb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_optrgb");
                Onicg_cap_optrgbChanged();
            }
        }
        private Nullable<global::System.Byte> _icg_cap_optrgb;
        partial void Onicg_cap_optrgbChanging(Nullable<global::System.Byte> value);
        partial void Onicg_cap_optrgbChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> icg_cap_shopdot
        {
            get
            {
                return _icg_cap_shopdot;
            }
            set
            {
                Onicg_cap_shopdotChanging(value);
                ReportPropertyChanging("icg_cap_shopdot");
                _icg_cap_shopdot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_shopdot");
                Onicg_cap_shopdotChanged();
            }
        }
        private Nullable<global::System.Byte> _icg_cap_shopdot;
        partial void Onicg_cap_shopdotChanging(Nullable<global::System.Byte> value);
        partial void Onicg_cap_shopdotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> icg_cap_shopprl
        {
            get
            {
                return _icg_cap_shopprl;
            }
            set
            {
                Onicg_cap_shopprlChanging(value);
                ReportPropertyChanging("icg_cap_shopprl");
                _icg_cap_shopprl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_shopprl");
                Onicg_cap_shopprlChanged();
            }
        }
        private Nullable<global::System.Byte> _icg_cap_shopprl;
        partial void Onicg_cap_shopprlChanging(Nullable<global::System.Byte> value);
        partial void Onicg_cap_shopprlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> icg_cap_shopfoa
        {
            get
            {
                return _icg_cap_shopfoa;
            }
            set
            {
                Onicg_cap_shopfoaChanging(value);
                ReportPropertyChanging("icg_cap_shopfoa");
                _icg_cap_shopfoa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_shopfoa");
                Onicg_cap_shopfoaChanged();
            }
        }
        private Nullable<global::System.Byte> _icg_cap_shopfoa;
        partial void Onicg_cap_shopfoaChanging(Nullable<global::System.Byte> value);
        partial void Onicg_cap_shopfoaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> icg_cap_shopdept
        {
            get
            {
                return _icg_cap_shopdept;
            }
            set
            {
                Onicg_cap_shopdeptChanging(value);
                ReportPropertyChanging("icg_cap_shopdept");
                _icg_cap_shopdept = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_shopdept");
                Onicg_cap_shopdeptChanged();
            }
        }
        private Nullable<global::System.Byte> _icg_cap_shopdept;
        partial void Onicg_cap_shopdeptChanging(Nullable<global::System.Byte> value);
        partial void Onicg_cap_shopdeptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> icg_cap_opt_prodesigner
        {
            get
            {
                return _icg_cap_opt_prodesigner;
            }
            set
            {
                Onicg_cap_opt_prodesignerChanging(value);
                ReportPropertyChanging("icg_cap_opt_prodesigner");
                _icg_cap_opt_prodesigner = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_opt_prodesigner");
                Onicg_cap_opt_prodesignerChanged();
            }
        }
        private Nullable<global::System.Byte> _icg_cap_opt_prodesigner;
        partial void Onicg_cap_opt_prodesignerChanging(Nullable<global::System.Byte> value);
        partial void Onicg_cap_opt_prodesignerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> icg_cap_opt_procontractor
        {
            get
            {
                return _icg_cap_opt_procontractor;
            }
            set
            {
                Onicg_cap_opt_procontractorChanging(value);
                ReportPropertyChanging("icg_cap_opt_procontractor");
                _icg_cap_opt_procontractor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_opt_procontractor");
                Onicg_cap_opt_procontractorChanged();
            }
        }
        private Nullable<global::System.Byte> _icg_cap_opt_procontractor;
        partial void Onicg_cap_opt_procontractorChanging(Nullable<global::System.Byte> value);
        partial void Onicg_cap_opt_procontractorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_hhear
        {
            get
            {
                return _icg_cap_hhear;
            }
            set
            {
                Onicg_cap_hhearChanging(value);
                ReportPropertyChanging("icg_cap_hhear");
                _icg_cap_hhear = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_hhear");
                Onicg_cap_hhearChanged();
            }
        }
        private global::System.String _icg_cap_hhear;
        partial void Onicg_cap_hhearChanging(global::System.String value);
        partial void Onicg_cap_hhearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> icg_cap_sms_sent
        {
            get
            {
                return _icg_cap_sms_sent;
            }
            set
            {
                Onicg_cap_sms_sentChanging(value);
                ReportPropertyChanging("icg_cap_sms_sent");
                _icg_cap_sms_sent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_sms_sent");
                Onicg_cap_sms_sentChanged();
            }
        }
        private Nullable<global::System.Byte> _icg_cap_sms_sent;
        partial void Onicg_cap_sms_sentChanging(Nullable<global::System.Byte> value);
        partial void Onicg_cap_sms_sentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> icg_cap_addate
        {
            get
            {
                return _icg_cap_addate;
            }
            set
            {
                Onicg_cap_addateChanging(value);
                ReportPropertyChanging("icg_cap_addate");
                _icg_cap_addate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_addate");
                Onicg_cap_addateChanged();
            }
        }
        private Nullable<global::System.DateTime> _icg_cap_addate;
        partial void Onicg_cap_addateChanging(Nullable<global::System.DateTime> value);
        partial void Onicg_cap_addateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> icg_cap_UpdateDT
        {
            get
            {
                return _icg_cap_UpdateDT;
            }
            set
            {
                Onicg_cap_UpdateDTChanging(value);
                ReportPropertyChanging("icg_cap_UpdateDT");
                _icg_cap_UpdateDT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_UpdateDT");
                Onicg_cap_UpdateDTChanged();
            }
        }
        private Nullable<global::System.DateTime> _icg_cap_UpdateDT;
        partial void Onicg_cap_UpdateDTChanging(Nullable<global::System.DateTime> value);
        partial void Onicg_cap_UpdateDTChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("rlworldwideModel", "FK_icg_marketing_data_supplement_icg_marketing_data", "icg_marketing_data_supplement")]
        public EntityCollection<icg_marketing_data_supplement> icg_marketing_data_supplement
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<icg_marketing_data_supplement>("rlworldwideModel.FK_icg_marketing_data_supplement_icg_marketing_data", "icg_marketing_data_supplement");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<icg_marketing_data_supplement>("rlworldwideModel.FK_icg_marketing_data_supplement_icg_marketing_data", "icg_marketing_data_supplement", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rlworldwideModel", Name="icg_marketing_data_sitenum")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class icg_marketing_data_sitenum : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new icg_marketing_data_sitenum object.
        /// </summary>
        /// <param name="icg_cap_num_id">Initial value of the icg_cap_num_id property.</param>
        /// <param name="icg_cap_number">Initial value of the icg_cap_number property.</param>
        public static icg_marketing_data_sitenum Createicg_marketing_data_sitenum(global::System.Int32 icg_cap_num_id, global::System.Int32 icg_cap_number)
        {
            icg_marketing_data_sitenum icg_marketing_data_sitenum = new icg_marketing_data_sitenum();
            icg_marketing_data_sitenum.icg_cap_num_id = icg_cap_num_id;
            icg_marketing_data_sitenum.icg_cap_number = icg_cap_number;
            return icg_marketing_data_sitenum;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 icg_cap_num_id
        {
            get
            {
                return _icg_cap_num_id;
            }
            set
            {
                if (_icg_cap_num_id != value)
                {
                    Onicg_cap_num_idChanging(value);
                    ReportPropertyChanging("icg_cap_num_id");
                    _icg_cap_num_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("icg_cap_num_id");
                    Onicg_cap_num_idChanged();
                }
            }
        }
        private global::System.Int32 _icg_cap_num_id;
        partial void Onicg_cap_num_idChanging(global::System.Int32 value);
        partial void Onicg_cap_num_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 icg_cap_number
        {
            get
            {
                return _icg_cap_number;
            }
            set
            {
                Onicg_cap_numberChanging(value);
                ReportPropertyChanging("icg_cap_number");
                _icg_cap_number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_number");
                Onicg_cap_numberChanged();
            }
        }
        private global::System.Int32 _icg_cap_number;
        partial void Onicg_cap_numberChanging(global::System.Int32 value);
        partial void Onicg_cap_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_site
        {
            get
            {
                return _icg_cap_site;
            }
            set
            {
                Onicg_cap_siteChanging(value);
                ReportPropertyChanging("icg_cap_site");
                _icg_cap_site = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_site");
                Onicg_cap_siteChanged();
            }
        }
        private global::System.String _icg_cap_site;
        partial void Onicg_cap_siteChanging(global::System.String value);
        partial void Onicg_cap_siteChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rlworldwideModel", Name="icg_marketing_data_supplement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class icg_marketing_data_supplement : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new icg_marketing_data_supplement object.
        /// </summary>
        /// <param name="icg_cap_Supplement_id">Initial value of the icg_cap_Supplement_id property.</param>
        /// <param name="icg_cap_id">Initial value of the icg_cap_id property.</param>
        /// <param name="icg_cap_RegisterforNews">Initial value of the icg_cap_RegisterforNews property.</param>
        /// <param name="icg_cap_Current_RL_customer">Initial value of the icg_cap_Current_RL_customer property.</param>
        public static icg_marketing_data_supplement Createicg_marketing_data_supplement(global::System.Int32 icg_cap_Supplement_id, global::System.Int32 icg_cap_id, global::System.Boolean icg_cap_RegisterforNews, global::System.Boolean icg_cap_Current_RL_customer)
        {
            icg_marketing_data_supplement icg_marketing_data_supplement = new icg_marketing_data_supplement();
            icg_marketing_data_supplement.icg_cap_Supplement_id = icg_cap_Supplement_id;
            icg_marketing_data_supplement.icg_cap_id = icg_cap_id;
            icg_marketing_data_supplement.icg_cap_RegisterforNews = icg_cap_RegisterforNews;
            icg_marketing_data_supplement.icg_cap_Current_RL_customer = icg_cap_Current_RL_customer;
            return icg_marketing_data_supplement;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 icg_cap_Supplement_id
        {
            get
            {
                return _icg_cap_Supplement_id;
            }
            set
            {
                if (_icg_cap_Supplement_id != value)
                {
                    Onicg_cap_Supplement_idChanging(value);
                    ReportPropertyChanging("icg_cap_Supplement_id");
                    _icg_cap_Supplement_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("icg_cap_Supplement_id");
                    Onicg_cap_Supplement_idChanged();
                }
            }
        }
        private global::System.Int32 _icg_cap_Supplement_id;
        partial void Onicg_cap_Supplement_idChanging(global::System.Int32 value);
        partial void Onicg_cap_Supplement_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 icg_cap_id
        {
            get
            {
                return _icg_cap_id;
            }
            set
            {
                Onicg_cap_idChanging(value);
                ReportPropertyChanging("icg_cap_id");
                _icg_cap_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_id");
                Onicg_cap_idChanged();
            }
        }
        private global::System.Int32 _icg_cap_id;
        partial void Onicg_cap_idChanging(global::System.Int32 value);
        partial void Onicg_cap_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean icg_cap_RegisterforNews
        {
            get
            {
                return _icg_cap_RegisterforNews;
            }
            set
            {
                Onicg_cap_RegisterforNewsChanging(value);
                ReportPropertyChanging("icg_cap_RegisterforNews");
                _icg_cap_RegisterforNews = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_RegisterforNews");
                Onicg_cap_RegisterforNewsChanged();
            }
        }
        private global::System.Boolean _icg_cap_RegisterforNews;
        partial void Onicg_cap_RegisterforNewsChanging(global::System.Boolean value);
        partial void Onicg_cap_RegisterforNewsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean icg_cap_Current_RL_customer
        {
            get
            {
                return _icg_cap_Current_RL_customer;
            }
            set
            {
                Onicg_cap_Current_RL_customerChanging(value);
                ReportPropertyChanging("icg_cap_Current_RL_customer");
                _icg_cap_Current_RL_customer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icg_cap_Current_RL_customer");
                Onicg_cap_Current_RL_customerChanged();
            }
        }
        private global::System.Boolean _icg_cap_Current_RL_customer;
        partial void Onicg_cap_Current_RL_customerChanging(global::System.Boolean value);
        partial void Onicg_cap_Current_RL_customerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_RL_Store
        {
            get
            {
                return _icg_cap_RL_Store;
            }
            set
            {
                Onicg_cap_RL_StoreChanging(value);
                ReportPropertyChanging("icg_cap_RL_Store");
                _icg_cap_RL_Store = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_RL_Store");
                Onicg_cap_RL_StoreChanged();
            }
        }
        private global::System.String _icg_cap_RL_Store;
        partial void Onicg_cap_RL_StoreChanging(global::System.String value);
        partial void Onicg_cap_RL_StoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_Subject
        {
            get
            {
                return _icg_cap_Subject;
            }
            set
            {
                Onicg_cap_SubjectChanging(value);
                ReportPropertyChanging("icg_cap_Subject");
                _icg_cap_Subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_Subject");
                Onicg_cap_SubjectChanged();
            }
        }
        private global::System.String _icg_cap_Subject;
        partial void Onicg_cap_SubjectChanging(global::System.String value);
        partial void Onicg_cap_SubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_Message
        {
            get
            {
                return _icg_cap_Message;
            }
            set
            {
                Onicg_cap_MessageChanging(value);
                ReportPropertyChanging("icg_cap_Message");
                _icg_cap_Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_Message");
                Onicg_cap_MessageChanged();
            }
        }
        private global::System.String _icg_cap_Message;
        partial void Onicg_cap_MessageChanging(global::System.String value);
        partial void Onicg_cap_MessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icg_cap_HeardAboutUs
        {
            get
            {
                return _icg_cap_HeardAboutUs;
            }
            set
            {
                Onicg_cap_HeardAboutUsChanging(value);
                ReportPropertyChanging("icg_cap_HeardAboutUs");
                _icg_cap_HeardAboutUs = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icg_cap_HeardAboutUs");
                Onicg_cap_HeardAboutUsChanged();
            }
        }
        private global::System.String _icg_cap_HeardAboutUs;
        partial void Onicg_cap_HeardAboutUsChanging(global::System.String value);
        partial void Onicg_cap_HeardAboutUsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("rlworldwideModel", "FK_icg_marketing_data_supplement_icg_marketing_data", "icg_marketing_data")]
        public icg_marketing_data icg_marketing_data
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<icg_marketing_data>("rlworldwideModel.FK_icg_marketing_data_supplement_icg_marketing_data", "icg_marketing_data").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<icg_marketing_data>("rlworldwideModel.FK_icg_marketing_data_supplement_icg_marketing_data", "icg_marketing_data").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<icg_marketing_data> icg_marketing_dataReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<icg_marketing_data>("rlworldwideModel.FK_icg_marketing_data_supplement_icg_marketing_data", "icg_marketing_data");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<icg_marketing_data>("rlworldwideModel.FK_icg_marketing_data_supplement_icg_marketing_data", "icg_marketing_data", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
